TrajectoryPlannerROS:
  # Robot velocity constraints
  max_vel_x: 1.0  # Lower than robot's actual max for better control - was 0.015
  min_vel_x: 0.05 # was 0.005
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.001
  
  # Acceleration limits
  acc_lim_theta: 0.3
  acc_lim_x: 0.5 # was 0.1
  acc_lim_y: 0.5 # was 0.1
  
  # Goal tolerance
  xy_goal_tolerance: 0.5 # was 0.2
  yaw_goal_tolerance: 0.3
  
  # Forward simulation parameters
  sim_time: 1.5
  sim_granularity: 0.025
  vx_samples: 6
  vtheta_samples: 20
  
  # Not a holonomic robot, but it can move laterally to some extent
  holonomic_robot: false
  
  # Visualization
  publish_cost_grid_pc: true
  
  # Score metrics by meter
  meter_scoring: true
  
  # Controller behavior
  pdist_scale: 0.8
  gdist_scale: 0.4
  occdist_scale: 0.05
  heading_lookahead: 0.3
  heading_scoring: false
  
  # Oscillation prevention
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1
  
  # Additional parameters for more stable movement
  dwa: false
  simple_attractor: false