TrajectoryPlannerROS:
  max_vel_x: 0.02  
  min_vel_x: 0.01
  max_vel_theta: 0.3 
  min_in_place_vel_theta: 0.2
  acc_lim_theta: 0.6
  acc_lim_x: 0.2
  acc_lim_y: 0.2
  holonomic_robot: false
  meter_scoring: true
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.3