obstacle_range: 2.5
raytrace_range: 3.0
# Define footprint as rectangle similar to robot dimensions
footprint: [[-0.12, -0.07], [-0.12, 0.07], [0.12, 0.07], [0.12, -0.07]]
inflation_radius: 0.3
transform_tolerance: 0.5

observation_sources: laser_scan_sensor
laser_scan_sensor: {
  sensor_frame: laser_frame, 
  data_type: LaserScan, 
  topic: /scan, 
  marking: true, 
  clearing: true,
  max_obstacle_height: 0.4,
  min_obstacle_height: 0.05,
  obstacle_range: 2.5,
  raytrace_range: 3.0
}